pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 9010:3000 -v ../../../../app/frontend/react:/var/www/html'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }

    }
}