version: '3.1'

services:

  db:
    image: postgres
    container_name: graphql-prisma-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: CARS
    ports:
      - 5432:5432
    volumes:
      - ../app/backend/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: graphql-prisma-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db